import fs from "node:fs/promises";
import path from "node:path";

// Hook stdin tool_name for MultiAgentV2 is flat_tool_name(namespace+name) with no
// separator: namespace "collaboration" + "spawn_agent" => "collaborationspawn_agent".
// V1 / plain spawn maps to HookToolName::spawn_agent() => "spawn_agent".
// `collaboration__spawn_agent` is the code-mode / UI label, not the hook matcher name.
const HOOK_MATCHER = "spawn_agent|collaborationspawn_agent|collaboration__spawn_agent";
const HOOK_STATUS = "Eco: apply orchestration role model";

/**
 * Install a Codex PreToolUse hook that forces `fork_turns="none"` on spawn_agent.
 *
 * Codex defaults omitted fork_turns to "all", which inherits the parent model and
 * rejects agent_type (openai/codex#20077). Eco writes orchestration models into
 * the thread's content-addressed agent config; the main agent only needs agent_type — this hook
 * applies the community workaround without teaching the model about fork_turns.
 *
 * Untrusted user hooks are skipped (discovery.rs). Eco therefore writes
 * `hooks.state.<key>.trusted_hash` into config.toml so the hook is Trusted.
 *
 * @see https://developers.openai.com/codex/hooks
 * @see https://github.com/openai/codex/issues/20077
 */
export async function syncCodexSpawnAgentHook(codexHomeDir: string): Promise<{
  hooksPath: string;
  scriptPath: string;
  trustKey: string;
  trustHash: string;
  trustTomlBlock: string;
}> {
  const hooksDir = path.join(codexHomeDir, "hooks");
  const scriptPath = path.join(hooksDir, "eco-spawn-agent-pretool.mjs");
  const hooksPath = path.join(codexHomeDir, "hooks.json");
  const command = `node ${JSON.stringify(scriptPath)}`;

  await fs.mkdir(hooksDir, { recursive: true });
  await writeUtf8FileIfChanged(scriptPath, ECO_SPAWN_AGENT_PRETOOL_SCRIPT);
  // Codex treats alphanumeric/_/| matchers as exact names (not substring regex).
  // Live MultiAgentV2 hook tool_name is `collaborationspawn_agent` (no `__`).
  await writeUtf8FileIfChanged(
    hooksPath,
    `${JSON.stringify(
      {
        hooks: {
          PreToolUse: [
            {
              matcher: HOOK_MATCHER,
              hooks: [
                {
                  type: "command",
                  command,
                  statusMessage: HOOK_STATUS,
                },
              ],
            },
          ],
        },
      },
      null,
      2,
    )}\n`,
  );

  // key_source is hooks.json path.display(); event label pre_tool_use; group 0; handler 0.
  const trustKey = `${hooksPath}:pre_tool_use:0:0`;
  const trustHash = await computeCodexCommandHookHash({
    matcher: HOOK_MATCHER,
    command,
    statusMessage: HOOK_STATUS,
  });
  const trustTomlBlock = [
    "",
    `# Eco-managed trust for spawn_agent PreToolUse (fork_turns=none injection).`,
    `[hooks.state.${tomlKey(trustKey)}]`,
    `trusted_hash = ${JSON.stringify(trustHash)}`,
    "",
  ].join("\n");

  return { hooksPath, scriptPath, trustKey, trustHash, trustTomlBlock };
}

async function writeUtf8FileIfChanged(filePath: string, content: string): Promise<void> {
  try {
    if ((await fs.readFile(filePath, "utf8")) === content) {
      return;
    }
  } catch (error) {
    if (!(error instanceof Error && "code" in error && error.code === "ENOENT")) {
      throw error;
    }
  }
  await fs.writeFile(filePath, content, "utf8");
}

/** Mirror codex-rs/config fingerprint::version_for_toml + hooks discovery::command_hook_hash. */
export async function computeCodexCommandHookHash(input: {
  matcher: string;
  command: string;
  statusMessage: string;
}): Promise<string> {
  // NormalizedHookIdentity { event_name, #[serde(flatten)] MatcherGroup }
  // HookHandlerConfig::Command with timeout defaulted to 600.
  const identity = {
    event_name: "pre_tool_use",
    matcher: input.matcher,
    hooks: [
      {
        type: "command",
        command: input.command,
        timeout: 600,
        async: false,
        statusMessage: input.statusMessage,
      },
    ],
  };
  const canonical = canonicalJson(identity);
  const serialized = Buffer.from(JSON.stringify(canonical));
  // Dynamic import: this module must not be statically reachable from renderer.
  const { createHash } = await import("node:crypto");
  const hex = createHash("sha256").update(serialized).digest("hex");
  return `sha256:${hex}`;
}

function canonicalJson(value: unknown): unknown {
  if (Array.isArray(value)) {
    return value.map(canonicalJson);
  }
  if (value && typeof value === "object") {
    const record = value as Record<string, unknown>;
    const sorted: Record<string, unknown> = {};
    for (const key of Object.keys(record).sort()) {
      sorted[key] = canonicalJson(record[key]);
    }
    return sorted;
  }
  return value;
}

function tomlKey(key: string): string {
  return JSON.stringify(key);
}

/** Node script: stdin PreToolUse payload → stdout updatedInput with fork_turns=none. */
const ECO_SPAWN_AGENT_PRETOOL_SCRIPT = `#!/usr/bin/env node
// Generated by Eco Coding. Do not edit.
// Forces fork_turns=none on spawn_agent so the selected custom-agent config applies.
import fs from "node:fs";
import path from "node:path";

const chunks = [];
for await (const chunk of process.stdin) {
  chunks.push(chunk);
}
const raw = Buffer.concat(chunks).toString("utf8").trim();
if (!raw) {
  process.stdout.write("{}");
  process.exit(0);
}

let payload;
try {
  payload = JSON.parse(raw);
} catch {
  process.stdout.write("{}");
  process.exit(0);
}

const toolName = String(payload.tool_name ?? payload.toolName ?? "");
// Matches spawn_agent, spawnAgent, collaborationspawn_agent, collaboration__spawn_agent.
const normalizedToolName = toolName.toLowerCase().replace(/_/g, "");
if (!normalizedToolName.includes("spawnagent")) {
  process.stdout.write("{}");
  process.exit(0);
}

const toolInput = readSpawnToolInput(payload);
const hasMessage =
  typeof toolInput.message === "string" && toolInput.message.trim().length > 0;
const hasTaskName =
  typeof toolInput.task_name === "string" && toolInput.task_name.trim().length > 0;
const hasAgentType =
  typeof toolInput.agent_type === "string" && toolInput.agent_type.trim().length > 0;

// Codex replaces the entire spawn_agent arguments with updatedInput. Never emit a
// partial object (e.g. only fork_turns) — that drops message/task_name and the
// child agent sees an empty task payload.
// Newer Codex spawn_agent calls may omit task_name and carry only agent_type +
// message. That is still enough to inject fork_turns=none and preserve role
// attribution.
if (!hasMessage || (!hasTaskName && !hasAgentType)) {
  try {
    const logPath = new URL("./eco-spawn-agent-pretool.log", import.meta.url);
    fs.appendFileSync(
      logPath,
      JSON.stringify({
        at: new Date().toISOString(),
        toolName,
        skippedRewrite: true,
        reason: "missing message or task_name in hook tool_input",
        agent_type: toolInput.agent_type ?? null,
        messageLength:
          typeof toolInput.message === "string" ? toolInput.message.length : 0,
        task_name: toolInput.task_name ?? null,
      }) + "\\n",
    );
  } catch {
    // best-effort diagnostics only
  }
  process.stdout.write(
    JSON.stringify({
      hookSpecificOutput: {
        hookEventName: "PreToolUse",
        permissionDecision: "allow",
      },
    }),
  );
  process.exit(0);
}

// Orchestration role models load only when fork is not full-history (codex#20077).
toolInput.fork_turns = "none";
// Role files own model/provider; strip overrides that confuse Codex built-in names.
delete toolInput.model;
delete toolInput.reasoning_effort;

const agentType =
  typeof toolInput.agent_type === "string" ? toolInput.agent_type.trim().toLowerCase() : "";
const codexHome = process.env.CODEX_HOME?.trim();
const toolUseId =
  typeof payload.tool_use_id === "string" ? payload.tool_use_id.trim() : "";
if (agentType && codexHome && toolUseId) {
  try {
    const queueDir = path.join(codexHome, "eco-pending-spawns");
    const payloadPath = path.join(
      queueDir,
      Buffer.from(toolUseId, "utf8").toString("base64url") + ".json",
    );
    fs.mkdirSync(queueDir, { recursive: true });
    fs.writeFileSync(
      payloadPath,
      JSON.stringify({
        agentRole: agentType,
        message: toolInput.message,
        task_name: toolInput.task_name ?? agentType,
        tool_use_id: toolUseId,
        at: Date.now(),
      }) + "\\n",
      { encoding: "utf8", flag: "wx" },
    );
  } catch {
    // Duplicate ids or diagnostics failures must not alter spawn arguments.
  }
}

try {
  const logPath = new URL("./eco-spawn-agent-pretool.log", import.meta.url);
  fs.appendFileSync(
    logPath,
    JSON.stringify({
      at: new Date().toISOString(),
      toolName,
      agent_type: toolInput.agent_type ?? null,
      fork_turns: toolInput.fork_turns,
      messageLength: toolInput.message.length,
      task_name: toolInput.task_name,
    }) + "\\n",
  );
} catch {
  // best-effort diagnostics only
}

function readSpawnToolInput(payload) {
  let raw = payload.tool_input ?? payload.toolInput;
  if (typeof raw === "string") {
    try {
      raw = JSON.parse(raw);
    } catch {
      return {};
    }
  }
  if (raw && typeof raw === "object" && !Array.isArray(raw)) {
    return { ...raw };
  }
  return {};
}

process.stdout.write(
  JSON.stringify({
    hookSpecificOutput: {
      hookEventName: "PreToolUse",
      permissionDecision: "allow",
      updatedInput: toolInput,
    },
  }),
);
`;
