import { expect, test } from "bun:test";
import {
  type FeedShape,
  outOfOrderRows,
  type RowShape,
  rowIdentity,
  sectionRows,
  toolRowIdentity,
} from "./support/feed-shape";
import { legacyOrderFor } from "./support/legacy-order";
import { type Corpus, corpusChainShapes, loadCorpus } from "./support/v2-corpus";

/**
 * The Feed-parity differential on real rows.
 *
 * The synthetic scenarios in `conversation-v2-projection-parity.test.ts` state the rules;
 * this runs the comparison over rows copied from real databases, because every defect that
 * reached the app was of the form "V2 drops or misplaces something real rows have and
 * synthetic rows did not". The corpus
 * (`test/fixtures/feed-parity/conversation-corpus.json`) is generated by
 * `scripts/feed-corpus-fixture.mjs`: real event types, scopes, roles, owners, stream
 * identities, tool names, metadata keys and times, with free text replaced by
 * content-addressed placeholders so a chat log does not have to live in the repository.
 *
 * Both sides are built from the same rows in the same fresh database:
 *
 * - old chain: the legacy projection merged with the V2 read models — what the Feed drew
 *   before the read side moved to V2;
 * - new chain: those rows through the production migrator, rendered from V2 alone.
 *
 * ## What is compared, and what is not
 *
 * 1. **Nothing is lost.** Every row identity the old chain renders — in the main feed or
 *    inside an agent card — must still be rendered somewhere. This is the property the
 *    reported defects violated (a prompt with no row, a subagent's tool inside the answer
 *    it was working for), and it does not depend on either chain's placement heuristics.
 * 2. **The main feed matches, row for row, in order.** Reportedly the hardest thing to get
 *    right and the thing a reader notices first.
 * 3. **The cards hold the same rows**, as a multiset per card, and **V2 is coherent on its
 *    own terms**: an agent-owned row is in that agent's card and not in the main feed;
 *    every rendered row carries the time it happened; sections and cards are in
 *    non-decreasing time order; a prompt the reader typed appears once.
 *
 * ## The differences that are excluded, and why
 *
 * Each of these is a difference *between the chains*, all of them the old chain's own
 * defects or limitations, and each is pinned by its own assertion rather than by weakening
 * the comparisons above (see `docs/plans/feed-regression-test-plan.md` §4.16):
 *
 * - **Prompt rows are duplicated** by the old chain: the prompt event row and the
 *   `thread_user_messages` row each become a row, and a rewound prompt can appear three
 *   times. They are deduplicated by text here, and V2 is separately required to render a
 *   prompt exactly once.
 * - **Agent-owned rows overflow into the main feed** in the old chain (the reported bug).
 *   They stay compared — as card rows — so a row that moved is never a row that vanished.
 * - **Times of tool rows**: the old chain positions read-model rows by "nearest surviving
 *   sibling", an approximation by construction. Tool rows are therefore compared by call
 *   identity and order, and V2's own rows are checked against the clock. Message rows are
 *   compared by time as well, because both chains know those times exactly.
 * - **A reasoning row can cover several thinking blocks**: consecutive thinking rows of one
 *   agent/attempt are merged into one row (with the blocks joined by a blank line). Whether
 *   two blocks end up adjacent depends on the rows between them, which is exactly what the
 *   overflow defect changes. Reasoning rows are therefore compared as blocks: the merged
 *   row's blocks are matched against the old chain's separate rows, and the merged row
 *   occupies one position in the order.
 */
const corpus: Corpus = loadCorpus();

const REASONING_ROLES = new Set(["thinking"]);

function isReasoning(row: RowShape): boolean {
  return REASONING_ROLES.has(row.role ?? "");
}

/** Every row the shape renders, feed and cards together. */
function allRows(shape: FeedShape): RowShape[] {
  return [...feedRows(shape), ...shape.cards.flatMap((card) => card.timeline)];
}

function feedRows(shape: FeedShape): RowShape[] {
  return shape.sections.flatMap((section) => sectionRows(section));
}

function identities(rows: readonly RowShape[]): string[] {
  return rows.map(rowIdentity);
}

/**
 * The row's content, as a multiset of the pieces a reader can see.
 *
 * A reasoning row is split into the blocks it covers, so a merged row counts as the blocks
 * it shows rather than as one unfamiliar string; a prompt row counts once no matter how
 * many times the chain drew it.
 */
function contentTokens(rows: readonly RowShape[]): string[] {
  const tokens: string[] = [];
  for (const row of rows) {
    if (isReasoning(row)) {
      for (const block of reasoningBlocks(row)) {
        tokens.push(`thinking|${block}`);
      }
      continue;
    }
    if (row.role === "user") {
      tokens.push(`user|${row.text}`);
      continue;
    }
    tokens.push(rowIdentity(row));
  }
  return dedupe(tokens).sort();
}

function reasoningBlocks(row: RowShape): string[] {
  return row.text
    .split("\n\n")
    .map((block) => block.trim())
    .filter(Boolean);
}

function dedupe(entries: readonly string[]): string[] {
  return [...new Set(entries)];
}

/**
 * The feed's rows as a comparison of what is in it, ignoring the order: agent-owned rows
 * removed (they belong to a card) and prompts counted once.
 */
function feedContents(rows: readonly RowShape[], agentOwned: ReadonlySet<string>): string[] {
  return contentTokens(rows.filter((row) => !(row.callId && agentOwned.has(row.callId))));
}

function difference(left: readonly string[], right: readonly string[]): string[] {
  const counts = new Map<string, number>();
  for (const entry of right) counts.set(entry, (counts.get(entry) ?? 0) + 1);
  const out: string[] = [];
  for (const entry of left) {
    const remaining = counts.get(entry) ?? 0;
    if (remaining > 0) {
      counts.set(entry, remaining - 1);
      continue;
    }
    out.push(entry);
  }
  return out;
}

// A conversation of a thousand rows is migrated, paged and rendered twice per test; the
// default five seconds is a property of the machine, not of the record being compared.
const CORPUS_TEST_TIMEOUT_MS = 60_000;
const corpusTest = (name: string, run: () => void): void => {
  test(name, run, CORPUS_TEST_TIMEOUT_MS);
};

for (const conversation of corpus.conversations) {
  const label = conversation.conversationId;
  const agentOwnedToolUseIds = agentOwnedToolUseIdsOf(conversation);
  const legacyOrder = legacyOrderFor(conversation.events);

  corpusTest(`${label}: V2 invents nothing`, () => {
    const { old, current } = corpusChainShapes(conversation);
    // This direction has no explanation available at all: a row V2 draws that the log never
    // had is fabricated. The other direction is checked row by row, below.
    expect(difference(contentTokens(allRows(current)), contentTokens(allRows(old)))).toEqual([]);
  });

  corpusTest(`${label}: every row V2 does not draw is recorded as something else`, () => {
    const { old, current } = corpusChainShapes(conversation);
    const dropped = difference(contentTokens(allRows(old)), contentTokens(allRows(current)));
    const byReason = new Map<DroppedRowReason, LegacyRow[]>();
    const unexplained: string[] = [];
    for (const token of dropped) {
      const explained = explainToken(conversation, token);
      if (!explained) {
        unexplained.push(`${token} (${sourceRowType(conversation, token) ?? "no source row"})`);
        continue;
      }
      byReason.set(explained.reason, [...(byReason.get(explained.reason) ?? []), explained.row]);
    }
    // Every row the old chain drew and V2 does not has to be a row the product itself does
    // not treat as content: a prompt, a message, a thinking block or a tool call has no
    // reason to be in this list, and one of them appearing here is a real loss.
    expect(unexplained).toEqual([]);

    const cards = new Set(current.cards.map((card) => card.key));
    const renderedCallIds = new Set(
      allRows(current)
        .map((row) => row.callId)
        .filter((callId): callId is string => Boolean(callId)),
    );
    for (const [reason, rows] of byReason) {
      if (process.env.CORPUS_CLASSIFY) {
        console.log(`CLASSIFY ${label} ${reason}=${rows.length}`);
      }
      // What the dropped row narrated has to be there: for a lifecycle line the agent and
      // its state, for a repeated row the call it repeats.
      if (reason === "agent-lifecycle") {
        for (const row of rows) {
          const agentId = String(row.agent_id ?? "").trim();
          // The card is keyed by the agent's registry id, which is the instance the row
          // names; when the log names a different id the instance table is the link.
          const registered = (conversation.agents as CorpusRow[]).find(
            (agent) =>
              String(agent.agent_id ?? "").trim() === agentId ||
              String(agent.parent_agent_id ?? "").trim() === agentId,
          );
          const key = String(registered?.agent_id ?? agentId).trim();
          expect(cards.has(key)).toBe(true);
        }
      }
      if (reason === "duplicate-call-row") {
        // The row without a call id repeats one that has it; that call is drawn as the card
        // the row's text belongs to, not as a row of its own.
        const spawnedCalls = new Set(
          current.cards
            .map((card) => card.parentToolUseId?.trim())
            .filter((callId): callId is string => Boolean(callId)),
        );
        for (const row of rows) {
          const callId = siblingCallId(conversation, row.message) ?? "";
          expect(renderedCallIds.has(callId) || spawnedCalls.has(callId)).toBe(true);
        }
      }
      if (reason === "session-status") {
        expect(current.attempts.length).toBeGreaterThan(0);
      }
    }
  });

  corpusTest(`${label}: the main feed holds the old chain's rows`, () => {
    const { old, current } = corpusChainShapes(conversation);
    // Which rows the main feed holds, not the order they end up in: the old chain positions
    // the rows the read models supply by "nearest surviving sibling", so its interleaving is
    // an approximation by construction. Order is asserted against the log itself, below.
    const agentOwned = cardIdentities(current);
    const currentFeed = feedContents(feedRows(current), agentOwned);
    const oldFeed = feedContents(feedRows(old), agentOwned);
    // Same rule as the conservation test: a row the feed does not hold is allowed only when
    // the product does not treat it as content (see `DroppedRowReason`).
    expect(
      difference(oldFeed, currentFeed).filter((token) => explainToken(conversation, token) === undefined),
    ).toEqual([]);
    expect(difference(currentFeed, oldFeed)).toEqual([]);
  });

  corpusTest(`${label}: the main feed keeps the log's order`, () => {
    // The authority for the order a conversation happened in is the legacy log's own
    // sequence, not either chain's projection: the Feed anchors a tool row at the call's
    // first row (its `tool.started`, or the approval that preceded it), so the rendered
    // times are not required to be sorted — the *rows* are.
    const order = legacyOrder;
    const { current } = corpusChainShapes(conversation);
    const misplaced: string[] = [];
    let previous = 0;
    for (const row of feedRows(current)) {
      // The turn's own output row is drawn after its process rows whatever its time is —
      // that is the renderer's design, shared by both chains, so it is not a position this
      // assertion can judge. It is compared as content, above.
      if (row.final) continue;
      const candidates = order.candidatesFor(row);
      if (candidates.length === 0) continue;
      const next = candidates.find((sequence) => sequence >= previous);
      if (process.env.CORPUS_DEBUG) {
        console.log(
          `  seq=${next ?? "-"} prev=${previous} ${rowIdentity(row).slice(0, 60)} candidates=[${candidates.slice(0, 6).join(",")}]`,
        );
      }
      if (next === undefined) {
        misplaced.push(`${rowIdentity(row)}: the log puts it before row ${previous}`);
        continue;
      }
      previous = next;
    }
    expect(misplaced).toEqual([]);
  });

  corpusTest(`${label}: the cards hold the same rows`, () => {
    const { old, current } = corpusChainShapes(conversation);
    // Cards are matched by the agent they are for, not by the order the projection lists
    // them in: the Feed sorts cards by their spawn anchor, which is a separate concern.
    const byKey = (shape: FeedShape) => new Map(shape.cards.map((card) => [card.key, card]));
    const currentByKey = byKey(current);
    const oldByKey = byKey(old);
    expect([...currentByKey.keys()].sort()).toEqual([...oldByKey.keys()].sort());
    const droppedWithoutReason: string[] = [];
    for (const [key, card] of currentByKey) {
      const oldCard = oldByKey.get(key);
      expect(`${card.role}:${card.status}`).toBe(`${oldCard?.role}:${oldCard?.status}`);
      const oldTokens = contentTokens(oldCard?.timeline ?? []);
      // The card must not invent a row either.
      expect(difference(contentTokens(card.timeline), oldTokens)).toEqual([]);
      for (const token of difference(oldTokens, contentTokens(card.timeline))) {
        const explained = explainToken(conversation, token);
        if (!explained) {
          droppedWithoutReason.push(`${key} ${token} (${sourceRowType(conversation, token) ?? "-"})`);
        }
      }
    }
    expect(droppedWithoutReason).toEqual([]);
  });

  corpusTest(`${label}: V2 is coherent on its own terms`, () => {
    const { current, userMessageIds } = corpusChainShapes(conversation);
    const rows = feedRows(current);
    // Ownership is a fact about the row, so a row whose call belongs to a subagent must be
    // in that agent's card. These assertions survive the old chain's deletion.
    expect(
      rows.filter((row) => row.callId !== undefined && agentOwnedToolUseIds.has(row.callId)).map(rowIdentity),
    ).toEqual([]);
    // No row may be drawn without the time it happened: that is what lets a reader — and
    // this test — put a message between the two tools of its own turn.
    expect(rows.filter((row) => !row.at).map(rowIdentity)).toEqual([]);
    for (const card of current.cards) {
      expect(card.timeline.filter((row) => !row.at).map(rowIdentity)).toEqual([]);
      expect(outOfOrderRows(card.timeline, `card ${card.key}`)).toEqual([]);
    }
    // Sections are ordered by their first row, and the rows inside them are checked
    // against the log's order (see the order test): their rendered times are the call's
    // own start, which can be earlier than a neighbouring message. What must hold here is
    // that no row is drawn without a time at all, which is what a row's position is made of.

    // Every prompt the read model holds is drawn exactly once. Text is not the identity: a
    // reader who sends the same short message twice wrote two prompts, and the Feed owes
    // them two rows — the *count* is what a duplicated prompt row breaks.
    // Compared as a multiset: *which* prompt the Feed draws where is the order test's job.
    const prompts = rows
      .filter((row) => row.role === "user")
      .map((row) => row.text)
      .sort();
    expect(prompts).toEqual([...userMessageIds].sort());
  });
}

/**
 * Why a legacy row the old chain drew has no row in V2.
 *
 * Each reason is a row the product itself does not treat as content, classified by an
 * earlier fix — and this test exists to keep that classification the *only* thing missing,
 * so that a real row (a prompt, a message, a thinking block, a tool call) can never
 * disappear behind one of these names:
 *
 * - `progress-narration`: a provider progress line (`todo.updated`, `sdkTaskKind
 *   task_progress`) the legacy log stored as a status or tool row. Invariant 15: it is not
 *   a tool call, and deriving one invents a call that never happened.
 * - `heartbeat`: alive-while-running rows, never the call itself.
 * - `agent-lifecycle`: "Subagent coder started" — the agent's own record carries the fact
 *   (status, start and end), which is what its card is drawn from.
 * - `session-status`: a `thread.status` line with `role=system`; the run and session state
 *   is the record of it.
 * - `duplicate-call-row`: the same call written twice, once without the call id.
 */
type DroppedRowReason =
  | "progress-narration"
  | "heartbeat"
  | "agent-lifecycle"
  | "session-status"
  | "duplicate-call-row";

interface LegacyRow extends CorpusRow {
  sequence: number;
  event_type: string;
  scope: string;
  role: string | null;
  agent_id: string | null;
  message: string | null;
  metadata_json: string | null;
}

function droppedRowReason(row: LegacyRow): DroppedRowReason | undefined {
  const metadata = parseJson(row.metadata_json);
  const liveType = typeof metadata?.liveType === "string" ? metadata.liveType : "";
  const tool = metadata?.tool as Record<string, unknown> | undefined;
  const toolUseId = typeof tool?.toolUseId === "string" ? tool.toolUseId.trim() : "";
  const message = (row.message ?? "").trim();
  if (liveType === "todo.updated" || metadata?.sdkTaskKind === "task_progress") {
    return "progress-narration";
  }
  if (toolUseId && /-heartbeat-\d+$/.test(toolUseId)) return "heartbeat";
  // The other heartbeat shape: no call id at all, the placeholder name the runtime uses for
  // a liveness row.
  if (row.event_type.startsWith("tool.") && !toolUseId && tool?.name === "Tool") {
    return "heartbeat";
  }
  if (row.event_type === "agent.started" || row.event_type === "agent.stopped") {
    return "agent-lifecycle";
  }
  if (row.event_type === "thread.status" && row.role === "system") {
    return "session-status";
  }
  // A tool row without a call id, repeating a call that also has one: the log writes the
  // enriched copy of a row without its identity.
  if (row.event_type.startsWith("tool.") && !toolUseId && message) {
    return "duplicate-call-row";
  }
  return undefined;
}

/**
 * The legacy row that explains a comparison token, and the reason it has no V2 row.
 *
 * A token names a tool call or a row of text, and the log can hold several rows behind one
 * text (the enriched copy of a tool row carries no call id). The token is explained when
 * *some* row with that identity is a row the product does not treat as content — and
 * unexplained when none of them is, which is what a lost message looks like.
 */
function explainToken(
  conversation: Corpus["conversations"][number],
  token: string,
): { row: LegacyRow; reason: DroppedRowReason } | undefined {
  const rows = conversation.events as LegacyRow[];
  const separator = token.indexOf("|");
  if (separator === -1) return undefined;
  const role = token.slice(0, separator);
  const rest = token.slice(separator + 1);
  if (!legacyRoles(conversation).has(role)) {
    const row = rows.find((candidate) => {
      const tool = parseJson(candidate.metadata_json)?.tool as Record<string, unknown> | undefined;
      return tool?.toolUseId === rest;
    });
    const reason = row ? droppedRowReason(row) : undefined;
    return row && reason ? { row, reason } : undefined;
  }
  // A row's rendered text is its message, or the call it names when the chain reduced a tool
  // row to its label.
  const matches = rows.filter((candidate) => (candidate.message ?? "").trim() === rest);
  const reduced = rows.filter((candidate) => toolRowIdentity((candidate.message ?? "").trim()) === rest);
  for (const row of [...matches, ...reduced]) {
    const reason = droppedRowReason(row);
    if (reason) return { row, reason };
  }
  return undefined;
}

/**
 * The roles the conversation's log writes rows with. A token's prefix is a tool call's
 * identity or the role of the row that wrote it, and which one it is comes from the log.
 */
function legacyRoles(conversation: Corpus["conversations"][number]): Set<string> {
  return new Set(
    (conversation.events as LegacyRow[]).map((row) => String(row.role ?? "").trim()).filter(Boolean),
  );
}

/** The call id a row without one repeats, by matching its text to a row that has it. */
function siblingCallId(
  conversation: Corpus["conversations"][number],
  message: string | null,
): string | undefined {
  for (const candidate of conversation.events as LegacyRow[]) {
    if ((candidate.message ?? "").trim() !== (message ?? "").trim()) continue;
    const tool = parseJson(candidate.metadata_json)?.tool as Record<string, unknown> | undefined;
    if (typeof tool?.toolUseId === "string" && tool.toolUseId.trim()) {
      return tool.toolUseId.trim();
    }
  }
  return undefined;
}

/** The legacy event type behind a token, for a failure message. */
function sourceRowType(conversation: Corpus["conversations"][number], token: string): string | undefined {
  const separator = token.indexOf("|");
  if (separator === -1) return undefined;
  const role = token.slice(0, separator);
  const rest = token.slice(separator + 1);
  const rows = conversation.events as LegacyRow[];
  if (legacyRoles(conversation).has(role)) {
    return rows.find((row) => (row.message ?? "").trim() === rest)?.event_type;
  }
  return rows.find((row) => {
    const tool = parseJson(row.metadata_json)?.tool as Record<string, unknown> | undefined;
    return tool?.toolUseId === rest;
  })?.event_type;
}

function parseJson(value: string | null | undefined): Record<string, unknown> | undefined {
  if (typeof value !== "string") return undefined;
  try {
    const parsed: unknown = JSON.parse(value);
    return parsed && typeof parsed === "object" && !Array.isArray(parsed)
      ? (parsed as Record<string, unknown>)
      : undefined;
  } catch {
    return undefined;
  }
}

/** Call identities the shape renders inside a card. */
function cardIdentities(shape: FeedShape): Set<string> {
  const out = new Set<string>();
  for (const card of shape.cards) {
    for (const row of card.timeline) {
      if (row.callId) out.add(row.callId);
    }
  }
  return out;
}

/**
 * Tool-call ids the corpus says belong to a *subagent*, which is the only owner that gets a
 * card. A planner instance is the attempt's own main agent, and its rows are the
 * conversation itself — the same distinction the legacy chain draws with `kind`.
 */
function agentOwnedToolUseIdsOf(conversation: Corpus["conversations"][number]): Map<string, string> {
  const subagentIds = new Set(
    conversation.agents
      .filter((agent) => String(agent.kind ?? "") !== "planner")
      .map((agent) => String(agent.agent_id ?? "").trim())
      .filter(Boolean),
  );
  const owners = new Map<string, string>();
  for (const event of conversation.events) {
    const agentId = typeof event.agent_id === "string" ? event.agent_id.trim() : "";
    if (!agentId || !subagentIds.has(agentId)) continue;
    const metadata = typeof event.metadata_json === "string" ? JSON.parse(event.metadata_json) : undefined;
    const tool = metadata?.tool as Record<string, unknown> | undefined;
    const toolUseId = typeof tool?.toolUseId === "string" ? tool.toolUseId.trim() : "";
    if (toolUseId) owners.set(toolUseId, agentId);
  }
  return owners;
}

test("the corpus covers the shapes the Feed has to keep", () => {
  const eventTypes = new Set(
    corpus.conversations.flatMap((conversation) => conversation.events.map((row) => String(row.event_type))),
  );
  // A corpus that quietly loses a class of row would turn this whole file into a weaker
  // test than it looks: assert the classes the reported defects came from are present.
  for (const required of [
    "tool.started",
    "tool.completed",
    "message.final",
    "thinking.final",
    "agent.started",
    "thread.status",
  ]) {
    expect(eventTypes.has(required)).toBe(true);
  }
  const roles = new Set(
    corpus.conversations.flatMap((conversation) => conversation.events.map((row) => String(row.role ?? ""))),
  );
  for (const required of ["planner", "coder", "explore", "tool", "user"]) {
    expect(roles.has(required)).toBe(true);
  }
  expect(corpus.conversations.some((entry) => entry.agents.length > 1)).toBe(true);
  expect(corpus.conversations.some((entry) => entry.attempts.length > 1)).toBe(true);
});
