import { expect, test } from "bun:test";
import { IPC_CHANNELS, isKnownIpcChannel } from "../src/shared/ipc";

test("declares the core desktop IPC channels", () => {
  expect(IPC_CHANNELS.workspaceOpen).toBe("workspace:open");
  expect(IPC_CHANNELS.workspacePrepareGit).toBe("workspace:prepare-git");
  expect(IPC_CHANNELS.modelSettingsGet).toBe("model-settings:get");
  expect(IPC_CHANNELS.modelProviderSave).toBe("model-provider:save");
  expect(IPC_CHANNELS.modelRouteProfileSave).toBe("model-route-profile:save");
  expect(IPC_CHANNELS.agentTemplateList).toBe("agent-template:list");
  expect(IPC_CHANNELS.agentTemplateSave).toBe("agent-template:save");
  expect(IPC_CHANNELS.agentTemplateDelete).toBe("agent-template:delete");
  expect(IPC_CHANNELS.agentTemplateExport).toBe("agent-template:export");
  expect(IPC_CHANNELS.agentTemplateImport).toBe("agent-template:import");
  expect(IPC_CHANNELS.agentTemplateVersionsList).toBe("agent-template-versions:list");
  expect(IPC_CHANNELS.agentTemplateVersionRestore).toBe("agent-template-version:restore");
  expect(IPC_CHANNELS.orchestrationProfileList).toBe("orchestration-profile:list");
  expect(IPC_CHANNELS.orchestrationProfileSave).toBe("orchestration-profile:save");
  expect(IPC_CHANNELS.orchestrationProfileDelete).toBe("orchestration-profile:delete");
  expect(IPC_CHANNELS.threadStart).toBe("thread:start");
  expect(IPC_CHANNELS.threadUpdateRuntimeConfig).toBe("thread:update-runtime-config");
  expect(IPC_CHANNELS.threadCancel).toBe("thread:cancel");
  expect(IPC_CHANNELS.threadRollbackTo).toBe("thread:rollback-to");
  expect(IPC_CHANNELS.threadApprovePlan).toBe("thread:approve-plan");
  expect(IPC_CHANNELS.threadGetUsageSnapshot).toBe("thread:get-usage-snapshot");
  expect(IPC_CHANNELS.threadRunProjectionGet).toBe("thread:run-projection-get");
  expect(IPC_CHANNELS.threadDismissPlan).toBe("thread:dismiss-plan");
  expect(IPC_CHANNELS.threadContinue).toBe("thread:continue");
  expect(IPC_CHANNELS.threadRetry).toBe("thread:retry");
  expect(IPC_CHANNELS.threadTodoList).toBe("thread:todo-list");
  expect(IPC_CHANNELS.clarificationGetPending).toBe("clarification:get-pending");
  expect(IPC_CHANNELS.clarificationSubmit).toBe("clarification:submit");
  expect(IPC_CHANNELS.clarificationDismiss).toBe("clarification:dismiss");
  expect(IPC_CHANNELS.subagentSettingsGet).toBe("subagent-settings:get");
  expect(IPC_CHANNELS.subagentSettingsSave).toBe("subagent-settings:save");
  expect(IPC_CHANNELS.workflowSettingsGet).toBe("workflow-settings:get");
  expect(IPC_CHANNELS.proxyBridgeSettingsGet).toBe("proxy-bridge-settings:get");
  expect(IPC_CHANNELS.workflowSettingsSave).toBe("workflow-settings:save");
  expect(IPC_CHANNELS.mcpSettingsGet).toBe("mcp-settings:get");
  expect(IPC_CHANNELS.skillsList).toBe("skills:list");
  expect(IPC_CHANNELS.skillsLinkAgents).toBe("skills:link-agents");
  expect(IPC_CHANNELS.mcpServerSave).toBe("mcp-server:save");
  expect(IPC_CHANNELS.sessionSyncSettingsGet).toBe("session-sync-settings:get");
  expect(IPC_CHANNELS.sessionSyncSettingsSave).toBe("session-sync-settings:save");
  expect(IPC_CHANNELS.sessionSyncTestConnection).toBe("session-sync:test-connection");
  expect(IPC_CHANNELS.modelProviderTest).toBe("model-provider:test");
  expect(IPC_CHANNELS.modelRouteProfileTest).toBe("model-route-profile:test");
  expect(IPC_CHANNELS.billingRefreshPricing).toBe("billing:refresh-pricing");
  expect(IPC_CHANNELS.billingRoutePricing).toBe("billing:route-pricing");
  expect(IPC_CHANNELS.billingRouteCapabilities).toBe("billing:route-capabilities");
  expect(IPC_CHANNELS.billingModelsDevList).toBe("billing:models-dev-list");
  expect(IPC_CHANNELS.approvalResolve).toBe("approval:resolve");
  expect(IPC_CHANNELS.conformanceRun).toBe("conformance:run");
});

test("guards unknown channels", () => {
  expect(isKnownIpcChannel("workspace:open")).toBe(true);
  expect(isKnownIpcChannel("model-settings:get")).toBe(true);
  expect(isKnownIpcChannel("thread:start")).toBe(true);
  expect(isKnownIpcChannel("unknown")).toBe(false);
});
